#Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

abstract_target 'defaults' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkyService
  pod 'Cartography'
  pod 'Eureka'
  pod 'SwiftHEXColors'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxUIAlert'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod "Chatto"
  pod "ChattoAdditions"
  pod 'RSKPlaceholderTextView'
  pod 'IQKeyboardManagerSwift'
  pod 'BetterSegmentedControl'

  target 'SkyService Pax'
  target 'SkyService Crew'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
       end
     end
 end
end
